services:
  sigic-frontend:
    image: sigic-frontend
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      NUXT_PUBLIC_BASE_URL: ${NUXT_PUBLIC_BASE_URL}
      NUXT_PUBLIC_GEONODE_URL: ${NUXT_PUBLIC_GEONODE_URL}
      NUXT_PUBLIC_GEONODE_API: ${NUXT_PUBLIC_GEONODE_API}
      NUXT_PUBLIC_GEOSERVER_URL: ${NUXT_PUBLIC_GEOSERVER_URL}
      NUXT_PUBLIC_IA_BACKEND_URL: ${NUXT_PUBLIC_IA_BACKEND_URL}
      NUXT_PUBLIC_DEFAULT_PAGE: ${NUXT_PUBLIC_DEFAULT_PAGE}
      NUXT_PUBLIC_GEONODE_API_DEFAULT_FILTER: ${NUXT_PUBLIC_GEONODE_API_DEFAULT_FILTER}
      NUXT_PUBLIC_ENABLE_AUTH: ${NUXT_PUBLIC_ENABLE_AUTH}
      NUXT_PUBLIC_ENABLE_CATALOGO_VISTA: ${NUXT_PUBLIC_ENABLE_CATALOGO_VISTA}
      NUXT_PUBLIC_ENABLE_CATALOGO_CARGA: ${NUXT_PUBLIC_ENABLE_CATALOGO_CARGA}
      NUXT_PUBLIC_ENABLE_CONSULTA: ${NUXT_PUBLIC_ENABLE_CONSULTA}
      NUXT_PUBLIC_ENABLE_IAA: ${NUXT_PUBLIC_ENABLE_IAA}
      NUXT_PUBLIC_ENABLE_LEVANTAMIENTO: ${NUXT_PUBLIC_ENABLE_LEVANTAMIENTO}
      NUXT_AUTH_ORIGIN: ${NUXT_AUTH_ORIGIN}
      NUXT_PUBLIC_AUTH_BASE_URL: ${NUXT_PUBLIC_AUTH_BASE_URL}
      KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      NUXT_AUTH_SECRET: ${NUXT_AUTH_SECRET}
      NUXT_PUBLIC_APP_BASE_PATH: ${NUXT_PUBLIC_APP_BASE_PATH}
